#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

"""revision:1573705075

Revision ID: 7b4263aa90c0
Revises: bbcb6050dfd1
Create Date: 2019-11-14 12:17:55.768004

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4263aa90c0'
down_revision = 'bbcb6050dfd1'
branch_labels = None
depends_on = None


def upgrade():
    """Apply revision:1573705075"""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('parent')
    op.add_column('sync_dag', sa.Column('task_json_str', sa.String(length=5000), nullable=True))
    # op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    """Unapply revision:1573705075"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('sync_dag', 'task_json_str')
    op.create_table('parent',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
